/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockVersionedContract__factory } from "./MockVersionedContract__factory";
export { VersionedContractTest__factory } from "./VersionedContractTest__factory";
