export { default as Actions } from './Actions'
export { default as Description } from './Description'
export { default as DetailsGrid } from './DetailsGrid'
export { default as Header } from './Header'
export { default as Navigation } from './Navigation'
export { default as ProposalCard } from './ProposalCard'
export { default as ProposalStatus } from './ProposalStatus'
