/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVersionedContract,
  IVersionedContractInterface,
} from "../IVersionedContract";

const _abi = [
  {
    inputs: [],
    name: "contractVersion",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IVersionedContract__factory {
  static readonly abi = _abi;
  static createInterface(): IVersionedContractInterface {
    return new utils.Interface(_abi) as IVersionedContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVersionedContract {
    return new Contract(address, _abi, signerOrProvider) as IVersionedContract;
  }
}
